# Generated by Django 5.0.4 on 2024-05-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0012_alter_invoice_net_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='gross_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
