# Generated by Django 5.0.4 on 2024-05-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0013_alter_invoice_gross_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='net_amount',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='unit_price',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
