# Generated by Django 5.0.4 on 2024-05-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0016_alter_invoice_gross_amount_alter_invoice_net_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='vat_rate',
            field=models.IntegerField(default=25),
        ),
    ]
