# Generated by Django 5.0.4 on 2024-05-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0017_alter_item_vat_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
