# Generated by Django 5.0.4 on 2024-05-26 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0018_alter_invoice_vat_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='bankaccount',
        ),
    ]
