# Generated by Django 5.0.4 on 2024-05-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0020_invoice_bankaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='bankaccount',
            field=models.CharField(blank=True, default=45669789, max_length=100, null=True),
        ),
    ]
